import type { Metadata } from "next"
import { Lato } from "next/font/google"
import "./globals.css"
import Navigation from "@/components/Navigation/Navigation"
import Header from "@/components/Header/Header"
import Template from "@/components/Template/Template"

const lato = Lato({
  subsets: ["latin"],
  weight: ["100", "300", "400", "700", "900"],
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={lato.className}>
        <Navigation />
        <Header />
        <Template>{children}</Template>
      </body>
    </html>
  )
}
